branches:
  only:
  - travis-test
sudo: false
git:
  quiet: true
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
addons:
  apt:
    packages:
      - autoconf
      - automake
      - libtool
      - pkg-config
      - curl
      - git
      - cmake
      - gcc
      - gperf
      - texinfo
      - yasm
      - nasm
      - bison
      - autogen
      - patch
  homebrew:
    packages:
      - autoconf
      - automake
      - libtool
      - pkg-config
      - curl
      - git
      - cmake
      - gcc
      - gperf
      - texinfo
      - yasm
      - nasm
      - bison
      - autogen
      - coreutils
    update: true
matrix:
  include:
    - name: "IOS Main Build"
      language: objective-c
      osx_image: xcode10.2
      before_script:
        - truncate --size 0 ./build.log
      script:
        - bash ./ios.sh -d
        - grep -e INFO ./build.log | grep build