branches:
  only:
  - travis-test
sudo: false
git:
  quiet: true
addons:
  apt:
    packages:
      - autoconf
      - automake
      - libtool
      - pkg-config
      - curl
      - git
      - cmake
      - gcc
      - gperf
      - texinfo
      - yasm
      - nasm
      - bison
      - autogen
      - patch
  homebrew:
    packages:
      - nasm
    update: true
matrix:
  include:
    - name: "iOS LTS Build"
      language: objective-c
      osx_image: xcode7.3
      before_script:
        - rm -f ./build.log
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./ios.sh
    - name: "iOS LTS Debug Build"
      language: objective-c
      osx_image: xcode7.3
      before_script:
        - rm -f ./build.log
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./ios.sh -d