# Only the whitelisted branches get built, regardless of build config
branches:
  only:
    - master

# Email the author if their commit either failed to build or fixed a failed build
# good -> bad, bad -> bad, bad -> good  but not  good -> good
notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

# Skip commits that don't affect the code / compiling the code
skip_commits:
  files:
    - .gitignore
    - .gitlab-ci.yml
    - .travis-install.bash
    - .travis.yml
    - COPYING
    - CREDITS
    - README.md
    - docs.doxy

# Download only a zip file of the latest commit
# Downloading the whole history of the repository would be unnecessary
shallow_clone: true

# Only try building the app, don't run any tests
test: off

# Don't bother with debug builds
configuration: 
  - Release

# Build with multiple compilers / build suites
image: Visual Studio 2015
environment:
  matrix:
    - platform: Win32
    - platform: x64
    - MSYSTEM: MINGW32
    - MSYSTEM: MINGW64

for:
-
  # MinGW builds need all kinds of build scripts
  matrix:
    only:
      - MSYSTEM: MINGW32
      - MSYSTEM: MINGW64

  install:
    # Update core packages
    - C:\msys64\usr\bin\pacman -Syyuu --noconfirm --noprogressbar
    # Update non-core packages
    - C:\msys64\usr\bin\pacman -Suu --noconfirm --noprogressbar
    # Install required MSYS2 packages
    - C:\msys64\usr\bin\pacman -S --noconfirm --noprogressbar --needed automake-wrapper make
    # Now MSYS2 is up to date, do the rest of the install from a bash script
    - C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./tools/appveyor-install.sh"

  build_script:
    - C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./tools/appveyor-build.sh"

  cache:
    - C:\msys64\var\cache\pacman\pkg
-
  # MSVC builds only need vsyasm and the solution file
  matrix:
    except:
      - MSYSTEM: MINGW32
      - MSYSTEM: MINGW64
  
  install:
    - ps: $url = "http://ultravideo.cs.tut.fi/vsyasm.exe"
    - ps: $output = "C:\Tools\vsyasm.exe"
    - ps: "(New-Object System.Net.WebClient).DownloadFile($url, $output)"
    - ps: '$env:Path += ";$output\.."'

  build:
    project: .\build\kvazaar_VS2015.sln
